### ISSUE TITLE
Sourcemaps support

### ISSUE THREAD

**Issue by matteofigus** [nickbalestra/infinite-loop-loader#3]
So that when the loader is in a chain of loaders, the source map properly maps the transformation.

**Comment by matteofigus** [comment]
To create sourcemaps, this project seems to be pretty good: https://github.com/mozilla/source-map#generating-a-source-map

**Comment by nickbalestra** [comment]
Nice. Here an example of how to add sourcemaps to falafel (using your suggest `source-map`) : https://github.com/alltom/node-falafel-map/commit/5b20ef21692410a2c04ecc80db9156a57754860c
